apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aareez-website
  name: aareez-website-svc
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 80
  selector:
    app: aareez-website
  type: NodePort
status:
  loadBalancer: {}
